### PR TITLE
CMR-72: Add deletes task to ingest dag.

### PR DESCRIPTION
**Pull request by dkinzer**
Depends on:

- [ ] https://github.com/tulibraries/centralized-metadata/pull/87

### CODE REVIEW

**Comment by dkinzer** [comment]
OK, I'm closing this and doing with no swagger changes.

**Comment by dkinzer** [comment]
wrong pr again.

**Comment by dkinzer** [comment]
oops.  yup.

**Comment by dkinzer** [comment]
I think I closed this by mistake again.

**Comment by dkinzer** [comment]
OK this solution required an deletes API endpoint that also works with records that are saved to a marc file.  That idea has been nixed so we need figure out another solution that satisfies the requirements of not using a marc delete endpoing.

**Comment by ebtoner** [comment]
@dkinzer -- please see my note on the Jira ticket. We could possibly approach it this way, but I think a bit more discussion is needed.

**Pull request merged**
